import {NextRequest, NextResponse} from "next/server";
import {getResponsiveCloudinaryUrl} from "./app/utils/optimizeCloudinaryImage";

const LEGACY_IMAGE_WIDTHS = [192, 384, 640, 960];

// Crawlers may keep requesting image URLs generated by older deployments.
// Redirect them before they can reach the retired image optimization endpoint.
export function proxy(request: NextRequest) {
    const src = request.nextUrl.searchParams.get("url");

    if (src === "/header-logo.png") {
        return NextResponse.redirect(new URL("/header-logo-small.webp", request.url), 308);
    }

    if (!src) return new NextResponse(null, {status: 404});

    let sourceUrl: URL;
    try {
        sourceUrl = new URL(src);
    } catch {
        return new NextResponse(null, {status: 404});
    }

    if (
        sourceUrl.protocol !== "https:"
        || sourceUrl.hostname !== "res.cloudinary.com"
        || sourceUrl.port
        || sourceUrl.username
        || sourceUrl.password
        || sourceUrl.search
        || sourceUrl.hash
    ) {
        return new NextResponse(null, {status: 404});
    }

    // Only accept our uploaded assets. Discard any old transformation prefix
    // so this redirect cannot be used to request arbitrary Cloudinary effects.
    const asset = sourceUrl.pathname.match(
        /^\/dnoxhtgef\/image\/upload\/(?:[^/]+\/)*(v\d+\/BlackBerry\/.+)$/,
    );
    if (!asset) return new NextResponse(null, {status: 404});

    const requestedWidth = Number(request.nextUrl.searchParams.get("w"));
    const width = Number.isSafeInteger(requestedWidth) && requestedWidth > 0
        ? requestedWidth
        : 640;
    const targetWidth = LEGACY_IMAGE_WIDTHS.find(candidate => candidate >= width) ?? 960;
    const originalUrl = `https://res.cloudinary.com/dnoxhtgef/image/upload/${asset[1]}`;

    return NextResponse.redirect(getResponsiveCloudinaryUrl(originalUrl, targetWidth), 308);
}

export const config = {
    matcher: "/_next/image",
};
